name: Compile

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven
      - uses: actions/checkout@v1
      - uses: AdoptOpenJDK/install-jdk@v1
        with:
          version: '8'
          architecture: x64
      - uses: actions/checkout@latest
      - uses: DeLaGuardo/setup-graalvm@3
        with:
          graalvm-version: '19.3.0.java8'
      - run: java -version
      - name: submodules-init
        uses: snickerbockers/submodules-init@v4
      - name: Build with Maven
        run: mvn -B package
      - name: Copy file to home directory
        run: mv bootstrap/spigot/target/Geyser-Spigot.jar ./
      - name: Archive artifacts (Spigot)
        uses: actions/upload-artifact@v2
        if: success()
        with:
          name: Geyser-Spigot
          path: ./Geyser-Spigot.jar
      - name: Push
        uses: github-actions-x/commit@v2.6
        if: success()
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push-branch: 'master'
          commit-message: 'Publish JAR file'
          force-add: 'true'
          files: ./Geyser-Spigot.jar
          name: GHActions
